timbuctoo-vre/src/main/java/nl/knaw/huygens/timbuctoo/index/solr/SolrIndex.java
timbuctoo-vre/src/test/java/nl/knaw/huygens/timbuctoo/index/solr/SolrIndexTest.java

However, I don't understand solr searches that should work still don't

Fixes searching for "rosie's" in autocomplete

---

.gitignore

This commit does change the meaning of some of the lines. I think
that this is closer to what the writer meant to achieve. In the
current source tree no new files are ignored and no ignored files
become unignored.

Cleans up gitignore

---

timbuctoo-model/src/main/java/nl/knaw/huygens/timbuctoo/model/charter/CharterDocument.java

Search used to have a workaround to get at these, but this commit makes NAC
use the same approach as NEWW

[NAC-24] Adds result date that the search results need

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/properties/JsonMetadata.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/properties/LocalProperty.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/properties/PropertyOrDefault.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/properties/ReadableProperty.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/properties/WwDocumentDisplayName.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/properties/WwPersonDisplayName.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/properties/converters/Converter.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/properties/converters/DefaultFullPersonNameConverter.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/properties/converters/DefaultLocationNameConverter.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/vre/Collection.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/vre/Vre.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/HuygensIng.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/TimbuctooV4.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/databasemigration/HuygensIngConfigToDatabaseMigration.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/model/properties/LocalPropertyTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/model/properties/ReadablePropertyTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/model/vre/CollectionTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/model/vre/VreTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/server/databasemigration/HuygensIngConfigToDatabaseMigrationIntegrationTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/server/databasemigration/HuygensIngConfigToDatabaseMigrationTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/util/TestGraphBuilder.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/util/VertexBuilder.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/util/VertexMatcher.java
timbuctoo-test-services/src/main/java/nl/knaw/huygens/hamcrest/LabelEqualityMatcher.java

@MMaas3 een goede extra check is om de traversals die in de unit tests zitten ook in de gremlin console uit te voeren. Dit is hoe ik tijdens het ontwikkelen steeds de nieuwe code heb gecheckt op correctheid.

Move config to database

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/TimbuctooV4.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/endpoints/v2/bulkupload/BulkUploadVre.java

Before merging. First fix issue TIM-1034, else this commit will break the Excel upload.

[TIM-1012] Check the users authorization before showing the information of the bulk upload.

---

timbuctoo-instancev4/src/main/scripts/index_scripts/README.md
timbuctoo-instancev4/src/main/scripts/index_scripts/samples/complete-sample-runner.rb
timbuctoo-instancev4/src/main/scripts/index_scripts/samples/indexer.rb
timbuctoo-instancev4/src/main/scripts/index_scripts/samples/solr.rb

`(here you write what the current situation is and what you don't like about it.
You might also put down in a few lines what your solution entails.)`
This issue is considered delivered when:
* `(Write verifiable statements that define when the issue is good enough to ship)`
`(Here you can put diagrams about the data that your code interacts with)`
```
Usually this section contains some ASCII art or images
```
1. `(A list of steps that you plan on taking in order to reach the goals)`

Finish solr docs

---

timbuctoo-instancev4/src/main/scripts/index_scripts/README.md

`(here you write what the current situation is and what you don't like about it.
You might also put down in a few lines what your solution entails.)`
This issue is considered delivered when:
* `(Write verifiable statements that define when the issue is good enough to ship)`
`(Here you can put diagrams about the data that your code interacts with)`
```
Usually this section contains some ASCII art or images
```
1. `(A list of steps that you plan on taking in order to reach the goals)`

sample indexer added.

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rml/README.adoc

The RML package should have a README explaining what it is, how to use it and what bugs are open.
This issue is considered delivered when:
* René can understands it and has used it to fix the circular dependency issue

Add README to RML package

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/DataStoreOperations.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rdf/SystemPropertyModifier.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/TimbuctooV4.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/databasemigration/PrepareForBiaImportMigration.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/endpoints/v2/bulkupload/ExecuteRml.java

Adds system configurations to support BIA data.

Prepare model for bia import

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/TinkerPopOperations.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/FulltextIndexChangeListener.java

-  	skip VERSION_OF and hasEntity edges for getOwnCollectionOfElement.
-  	remove older version from fulltext index in onRemoveFromCollection.

Fix entity delete

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/core/DataStoreOperations.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/core/RdfImportErrorReporter.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/core/RdfImportSession.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/core/dto/dataset/Collection.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/TinkerPopOperations.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/model/vre/Vre.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rdf/CollectionDescription.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rdf/Entity.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rdf/tripleprocessor/CollectionMembershipTripleProcessor.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rdf/tripleprocessor/TripleProcessorImpl.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/TinkerPopOperationsTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/ChangeListenerTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/model/vre/VreStubs.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/rdf/TripleImporterIntegrationTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/rdf/tripleprocessor/CollectionMembershipTripleProcessorTest.java

*Note*
This branch introduces a new vertex under the Vre vertex:
- linked with edge named: hasPredicateValueTypeVertex
- this new vertex now contains the hasPredicate edge and its descendants
- this new vertex replaces the use of the unknown collection for this purpose

Remove unknown entity

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/IndexHandler.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/Neo4jIndexHandler.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/TinkerPopOperations.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/VertexDuplicator.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/AddLabelChangeListener.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/ChangeListener.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/CollectionHasEntityRelationChangeListener.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/CompositeChangeListener.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/FulltextIndexChangeListener.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/IdIndexChangeListener.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/RdfIndexChangeListener.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/TimbuctooV4.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/databasemigration/IndexAllTheDisplaynames.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/databasemigration/IndexRelationsById.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/Neo4JIndexHandlerTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/TinkerPopOperationsStubs.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/TinkerPopOperationsTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/ChangeListenerTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/FulltextIndexChangeListenerTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/changelistener/IdIndexChangeListenerTest.java

Add the edges to an id index and reads them from it.

Edge index

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/core/EntityFinisherHelper.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/core/dto/rdf/RdfProperty.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/core/rdf/PropertyFactory.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/database/tinkerpop/TinkerPopOperations.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rdf/Database.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rdf/conversion/README.adoc
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/rdf/conversion/RdfPropertyConverterFactory.java

This is a quickfix to make this feature demo ready.

Make sure the types supported by Timbuctoo are saved the right way

---

README.adoc

"Getting Started" instructions (and a FAQ section) added to the Readme file.

Getting started merge fix

---

README.adoc

Changed the instructions in the readme file for uploading data to timbuctoo to reflect recent changes to the system.

updated README to reflect changes to data creation/upload endpoints

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dataset/dto/DataSet.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/datastores/implementations/RdfDescriptionSaver.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/datastores/resourcesync/ResourceSync.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/datastores/resourcesync/ResourceSyncXmlHelper.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/datastores/resourcesync/SourceDescriptionFile.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/dataset/DataSetRepositoryTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/datastores/implementations/RdfDescriptionSaverTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/datastores/resourcesync/SourceDescriptionFileTest.java

Resourcesync description

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dropwizard/endpoints/GraphQl.java

request:
```
curl 'http://localhost:8080/v5/graphql' \
-H 'Authorization: fake' \
-H 'accept: ' \
-H "Content-Type: application/json" \
-d '{
"query": "query { availableExportMimetypes { name } }"
}'
```
response before bug-fix: `{"code":500...` response after bug-fix: `{"data":{"contents"...`

graphql-bug

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dataset/ImportManager.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dataset/dto/DataSet.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/datastores/resourcesync/ResourceSync.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dropwizard/endpoints/ResourceSyncEndpoint.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/filestorage/FileStorage.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/filestorage/implementations/filesystem/FileSystemFileStorage.java
timbuctoo-instancev4/src/spec/java/nl/knaw/huygens/timbuctoo/v5/graphql/datafetchers/LookUpSubjectByUriFetcherWrapperTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/dataset/ImportManagerTest.java

- FileStorage returns Optional CachedFile
Prepare for fix of potential hack (ResourceSync.getFile creates directories):
- DataSet returns FileStorage

Bugfix null FileInfo:

---

documentation/design/resourcesync.adoc

See https://github.com/HuygensING/timbuctoo/blob/resourcesync_design/documentation/design/resourcesync.adoc

Disable ResourceSync for private dataSets - design

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/CollectionMetadataMutation.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/DataSetDescriptionMutation.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/ExtendSchemaMutation.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/IndexConfigMutation.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/MutationHelpers.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/PredicateMutationRdfPatcher.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/SummaryPropsMutation.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/ViewConfigMutation.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/dto/PredicateMutation.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/rootquery/RootQuery.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/rootquery/dataproviders/ViewConfigFetcher.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/util/RdfConstants.java
timbuctoo-instancev4/src/main/resources/nl/knaw/huygens/timbuctoo/v5/graphql/rootquery/schema.graphql

Together this makes it workable for people to configure the screens themselves

Description mutation + viewconfig on the server

---

docker-compose.yml
documentation/design/dynamic-graphql-queries.adoc
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/datafetchers/RdfWiringFactory.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/datafetchers/berkeleydb/datafetchers/DynamicRelationDataFetcher.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/datafetchers/dto/PaginatedDynamicList.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/derivedschema/DerivedQueryObjectTypeSchemaGenerator.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/derivedschema/DerivedSchemaContainer.java
timbuctoo-instancev4/src/main/resources/nl/knaw/huygens/timbuctoo/v5/graphql/rootquery/schema.graphql

see the design doc for more info

Dynamic query

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/GraphQlToRdfPatch.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/GraphQlToRdfPatchTest.java

See also commit https://github.com/HuygensING/timbuctoo/commit/d8262550b63e9d2169bba2d200b0064ad8ce323f

Deletion of values before addition of values

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/datastores/prefixstore/TypeNameStore.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/datastores/schemastore/dto/Type.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/datafetchers/RdfWiringFactory.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/derivedschema/DerivedSchemaContainer.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/DefaultIndexConfigMutation.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/MutationHelpers.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/PredicateMutationRdfPatcher.java
timbuctoo-instancev4/src/main/resources/nl/knaw/huygens/timbuctoo/v5/graphql/rootquery/schema.graphql

Add a possibility to reset the index to a default.

Auto index title

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/server/TimbuctooV4.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/berkeleydb/BdbEnvironmentCreator.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/berkeleydb/BdbPersistentEnvironmentCreator.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/berkeleydb/BdbWrapper.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dataset/DataSetRepository.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dataset/dto/DataSet.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dataset/dto/DataSetMetaData.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dataset/exceptions/DataSetCreationException.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/datastorage/DataStorage.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/datastorage/implementations/filesystem/FileSystemDataStorage.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dropwizard/endpoints/auth/AuthCheck.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dropwizard/healthchecks/DatabaseAvailabilityCheck.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dropwizard/tasks/ReloadDataSet.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/dropwizard/tasks/StopBdbDataStore.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/filehelper/FileHelper.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/CreateDataSetMutation.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/mutations/ResourceSyncImportMutation.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/dataset/DataSetRepositoryTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/dropwizard/BdbNonPersistentEnvironmentCreator.java

Be able to handle closed databases and make sure a data set cannot overwrite a data set that is still being deleted

Create set check

---

timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/elasticsearch/ElasticSearchFilter.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/elasticsearch/EsFilterResult.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/collectionfilter/FilterResult.java
timbuctoo-instancev4/src/main/java/nl/knaw/huygens/timbuctoo/v5/graphql/datafetchers/berkeleydb/datafetchers/CollectionDataFetcher.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/IntegrationTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/elasticsearch/ElasticSearchFilterTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/elasticsearch/EsFilterResultTest.java
timbuctoo-instancev4/src/test/java/nl/knaw/huygens/timbuctoo/v5/elasticsearch/FilterResultTest.java

Fixes the previous and next cursors

Browse next cursor fix
